version: 2.1

# Pipeline template
shared: &shared
    docker:
        - image: continuumio/miniconda3
          environment:
             BASH_ENV: ~/.bashrc
    working_directory: ~/pipeline_wd.ci
    steps:
        - checkout
        - run:
            name: "Setup Environment"
            command: |
                conda create -n ci ${CI_PYTHON} -c https://conda.anaconda.org/conda-forge -c defaults -c anaconda -y
                conda install -n ci ${CI_PYTEST} -c https://conda.anaconda.org/conda-forge -c defaults -c anaconda -y
                conda install -n ci wheel -c https://conda.anaconda.org/conda-forge -c defaults -c anaconda -y
                conda install -n ci --file requirements.txt -c https://conda.anaconda.org/conda-forge -c defaults -c anaconda -y
                conda init bash
        - run:
            name: "Prepare Project"
            command: |
                conda activate ci
                python setup.py develop
        - run:
            name: "Testing"
            command: |
                conda init bash
                conda activate ci
                mkdir test-results
                pytest --junit-xml=test-results/junit.xml
        - store_test_results:
            path: test-results
        - store_artifacts:
            path: test-results

# Workflow definition
workflows:
    standard:
        jobs:
            - cfm_ospo_demo_project-py35-pytest53 
            - cfm_ospo_demo_project-py36-pytest53 
            - cfm_ospo_demo_project-py37-pytest53 
            - cfm_ospo_demo_project-py38-pytest53 
            - cfm_ospo_demo_project-py39-pytest53 
    nightly:
        triggers:
            - schedule:
                cron: "0 0 * * *"
                filters:
                    branches:
                        only:
                            - master
        jobs:
            - nightly_build

# Jobs definition
jobs:
    
    cfm_ospo_demo_project-py35-pytest53:
        environment:
            CI_PYTHON: 'python=3.5'
            CI_PYTEST: 'pytest=5.3'
        <<: *shared
    cfm_ospo_demo_project-py36-pytest53:
        environment:
            CI_PYTHON: 'python=3.6'
            CI_PYTEST: 'pytest=5.3'
        <<: *shared
    cfm_ospo_demo_project-py37-pytest53:
        environment:
            CI_PYTHON: 'python=3.7'
            CI_PYTEST: 'pytest=5.3'
        <<: *shared
    cfm_ospo_demo_project-py38-pytest53:
        environment:
            CI_PYTHON: 'python=3.8'
            CI_PYTEST: 'pytest=5.3'
        <<: *shared
    cfm_ospo_demo_project-py39-pytest53:
        environment:
            CI_PYTHON: 'python=3.9'
            CI_PYTEST: 'pytest=5.3'
        <<: *shared
    nightly_build:
        environment:
            CI_PYTHON: 'python'
            CI_PYTEST: 'pytest'
        <<: *shared
